
CREATE TABLE `TAAA_ADMIN_USER` (
  `USER_ID` varchar(20) NOT NULL,
  `NAME` varchar(20) NOT NULL,
  `PASSWORD` varchar(500) NOT NULL,
  `CONTACT` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `COMMENT` longtext,
  `LAST_LOGIN_DATE` datetime DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) DEFAULT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) DEFAULT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `FK1vwyvoqk7f8o9f8a5ru3m2b8p` (`EDIT_USER_ID`),
  KEY `FKdnl86rxvfncuj57goiu4sbuc8` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE `TAAB_ADMIN_USER_MENU` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(20) DEFAULT NULL,
  `MENU_ADMIN_SEQ` int(11) DEFAULT NULL,
  `READ_FLAG` char(1) NOT NULL,
  `WRITE_FLAG` char(1) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK4wqhs3iaa9b1vkxh0fd1t26rw` (`EDIT_USER_ID`),
  KEY `FK39md6be677299fl06sg0rils0` (`MENU_ADMIN_SEQ`),
  KEY `FKq4lwln2wbmxhe79jbd3nawk76` (`REG_USER_ID`),
  KEY `FKnx051yqeouaugi8gk9vetruou` (`USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TABA_CODE_MASTER` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `MASTER_CODE` varchar(10) NOT NULL,
  `MASTER_CODE_NAME` varchar(10) NOT NULL,
  `MASTER_CODE_DES` varchar(500) NOT NULL,
  `SYSTEM_CODE_FLAG` char(1) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK4y4vjck4nbspsrbp9dlp7ck8q` (`EDIT_USER_ID`),
  KEY `FKe5qcxjqjbmq5o350jfp87u8an` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TABB_CODE_SLAVE` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `SLAVE_CODE` varchar(10) NOT NULL,
  `SLAVE_CODE_NAME` varchar(10) NOT NULL,
  `SLAVE_CODE_DES` varchar(500) NOT NULL,
  `MASTER_CODE` varchar(10) NOT NULL,
  `CODE_ORDER` int(11) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKmyoock6098rh00791t5wgnw4i` (`EDIT_USER_ID`),
  KEY `FKtmk0xtdsvyb3o5hf23bshl2nn` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TABC_CODE_SLAVE_INFO` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `MASTER_CODE` varchar(10) NOT NULL,
  `SLAVE_CODE` varchar(10) NOT NULL,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `INFO_NAME` varchar(100) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK50ru1p67pt2osor4xsbfi3qjo` (`EDIT_USER_ID`),
  KEY `FK9aaprjy46fkuk2rjfoseg13g6` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TACA_ADMIN_MENU` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `MENU_NAME` varchar(50) NOT NULL,
  `MENU_ORDER` int(11) NOT NULL,
  `MENU_URL` varchar(500) DEFAULT NULL,
  `PARENT_SEQ` int(11) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKjy7jdv4rrfnus8he1ind9bk72` (`EDIT_USER_ID`),
  KEY `FK8kwmh71k2jxnl45gu30i0xot8` (`PARENT_SEQ`),
  KEY `FK3ti2d4q1ptfo5w958haisakv5` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TACB_MENU` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `MENU_NAME` varchar(50) NOT NULL,
  `MENU_ORDER` int(11) NOT NULL,
  `MENU_LEVEL` int(11) NOT NULL,
  `MENU_URL` varchar(500) DEFAULT NULL,
  `CODE_MENU_TYPE` varchar(10) NOT NULL,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `CODE_LOGIN_TYPE` varchar(10) NOT NULL,
  `PARENT_SEQ` int(11) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKpf53ui6lqhfg1hfg0m6wo17wv` (`EDIT_USER_ID`),
  KEY `FKfa4pefl8avcgvbw4r4d620jv` (`PARENT_SEQ`),
  KEY `FK27tplwh94o47u1s289rial2i3` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TADA_ADMIN_ROLE` (
  `ROLE_NAME` varchar(20) NOT NULL,
  `ROLE_DESC` varchar(100) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) DEFAULT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) DEFAULT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`ROLE_NAME`),
  KEY `FKihslilsaalo6tfqrcv6uaayl` (`EDIT_USER_ID`),
  KEY `FKbnxbvhhtdkfnbj05s6g0qd53n` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TADB_ADMIN_ROLE_MENU` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(20) DEFAULT NULL,
  `MENU_ADMIN_SEQ` int(11) DEFAULT NULL,
  `READ_FLAG` char(1) NOT NULL,
  `WRITE_FLAG` char(1) NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK13wrbor8epj5f8t320c7mdj1r` (`EDIT_USER_ID`),
  KEY `FKn0j3l7060a1p9qb5p9apcgegg` (`MENU_ADMIN_SEQ`),
  KEY `FKp2uuoeuwe3ukjw86rdccruu9h` (`REG_USER_ID`),
  KEY `FKjsbd6ivs8lpsmp37t0p5ra8ok` (`ROLE_NAME`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TBAA_HISTORY` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `YEAR` varchar(4) NOT NULL,
  `MONTH` varchar(2) NOT NULL,
  `END_YEAR` varchar(4) DEFAULT NULL,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `CONTENT` varchar(200) NOT NULL,
  `PRINT_ORDER` int(11) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKee0k8y78gkqdyc141ktj9an6p` (`EDIT_USER_ID`),
  KEY `FKao17atyf2p42lq0kdbhiwxwkb` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TCAA_STAFFS` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_CENTER_TYPE` varchar(10) NOT NULL,
  `CODE_PART_TYPE` varchar(10) NOT NULL,
  `MASTER_FLAG` char(1) NOT NULL,
  `NAME` varchar(10) NOT NULL,
  `PRINT_ORDER` int(11) NOT NULL,
  `IMAGE_PATH` varchar(500) NOT NULL,
  `THUM_IMAGE_PATH` varchar(500) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKhmkp8erws091v1y4rosdouijs` (`EDIT_USER_ID`),
  KEY `FKdknqpvb2bsnhbxbssc09v8isy` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TCAB_STAFFS_INFO` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `POSITION` varchar(100) NOT NULL,
  `NAME` varchar(30) NOT NULL,
  `DEGREE` varchar(30) NOT NULL,
  `SPECIALTY` varchar(100) NOT NULL,
  `STAFFS_SEQ` int(11) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKd43sadvexqs11fxnk4hj498pn` (`EDIT_USER_ID`),
  KEY `FKkut7yfxan4gnktfla5o7p6mdp` (`REG_USER_ID`),
  KEY `FKe2r925utxrvuv0hmk9cdux6yg` (`STAFFS_SEQ`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TCAC_STAFFS_HISTORY` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `NOW_FLAG` char(1) NOT NULL,
  `CONTENT` varchar(100) NOT NULL,
  `COMMENT` varchar(100) NOT NULL,
  `PRINT_ORDER` int(11) NOT NULL,
  `STAFFS_SEQ` int(11) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK303sr7uy6niry4dig7bre3wws` (`EDIT_USER_ID`),
  KEY `FK7ilmvd7k04f6hnnexrg9b8auf` (`REG_USER_ID`),
  KEY `FKonjxxgxhensi2nu9xnddb1kl2` (`STAFFS_SEQ`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TDAA_CERTIFICATION` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `CODE_CENTER_TYPE` varchar(10) NOT NULL,
  `CODE_CERT_LOC_TYPE` varchar(10) DEFAULT NULL,
  `CODE_CERT_TYPE` varchar(10) NOT NULL,
  `TITLE` varchar(120) NOT NULL,
  `ISSUING_AGENCY` varchar(100) DEFAULT NULL,
  `CONTENT` varchar(500) NOT NULL,
  `PRINT_FLAG` char(1) NOT NULL,
  `PRINT_ORDER` int(11) NOT NULL,
  `FILE_PATH` varchar(500) NOT NULL,
  `FILE_NAME` varchar(200) NOT NULL,
  `THUM_FILE_PATH` varchar(500) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK83hl9jiehlc1bn6ixnbdw6ajf` (`EDIT_USER_ID`),
  KEY `FKookviaofpn5bi2y7diwoyyovy` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TEAA_BOARD_NOTICE` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `CODE_CENTER_TYPE` varchar(10) NOT NULL,
  `NOTICE_NUMBER` varchar(100) NOT NULL,
  `NOTICE_FLAG` char(1) NOT NULL,
  `TITLE` varchar(500) NOT NULL,
  `CONTENT` longtext NOT NULL,
  `HIT_CNT` bigint(20) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKrmv276p9xu57oldmpspacmjw7` (`EDIT_USER_ID`),
  KEY `FKojn5v364f7h0wg1pviyb8oc3w` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TEAB_BOARD_NOTICE_FILE` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `FILE_PATH` varchar(500) NOT NULL,
  `FILE_NAME` varchar(200) NOT NULL,
  `FILE_SIZE` bigint(20) NOT NULL,
  `DOWN_CNT` int(11) NOT NULL,
  `BOARD_NOTICE_SEQ` int(11) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK35m4udcieujgklf99mp0xug66` (`BOARD_NOTICE_SEQ`),
  KEY `FKlj154jk2bam2wkhlgsqawp1ug` (`EDIT_USER_ID`),
  KEY `FK2wqcimmgt05spyfm9fomfi0w3` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TEBA_BOARD_RECRUIT` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `CODE_RECRUIT_TYPE` varchar(10) NOT NULL,
  `CODE_RECRUIT_STATE_TYPE` varchar(10) NOT NULL,
  `TITLE` varchar(500) NOT NULL,
  `CONTENT` longtext,
  `CONTENT_TITLE` varchar(50) DEFAULT NULL,
  `CONTENT_COMMENT` varchar(50) DEFAULT NULL,
  `HIT_CNT` bigint(20) NOT NULL,
  `VIEW_FLAG` char(1) NOT NULL,
  `INPUT_TYPE_FLAG` char(1) NOT NULL,
  `START_DATE` datetime NOT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKg9pmcu5l811p2by4pqowr22pa` (`EDIT_USER_ID`),
  KEY `FK1jcad5tgr6ofuyv5i4f3e8gqv` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TEBB_BOARD_RECRUIT_TASK` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `TASK_SECTION` varchar(50) NOT NULL,
  `TASK_LOC` varchar(50) NOT NULL,
  `TASK_ASSIGNED` varchar(200) NOT NULL,
  `TASK_TIME` varchar(200) NOT NULL,
  `TASK_REQUIRE` varchar(500) NOT NULL,
  `TASK_OPTION` varchar(500) NOT NULL,
  `TASK_APES` varchar(500) NOT NULL,
  `BOARD_RECRUIT_SEQ` int(11) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK30omtgwrngwfg3iw6viplf8we` (`BOARD_RECRUIT_SEQ`),
  KEY `FK8cni2jqsrmc7yqykckebxakur` (`EDIT_USER_ID`),
  KEY `FKbg9keqcbl5ydi110bqp4wjc6i` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TECA_BOARD_DEFAULT_MASTER` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `MASTER_NAME` varchar(20) NOT NULL,
  `MASTER_DESC` varchar(500) DEFAULT NULL,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `OPT_NOTI_FLAG` char(1) NOT NULL,
  `OPT_THUM_FLAG` char(1) NOT NULL,
  `OPT_FILE_FLAG` char(1) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKokcq7173f9xmfobi6xqsg3bgk` (`EDIT_USER_ID`),
  KEY `FK9sv4gwj950iis4ny4k9cx6q8c` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TECB_BOARD_DEFAULT_SLAVE` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `BOARD_DEFAULT_MASTER_SEQ` int(11) DEFAULT NULL,
  `TITLE` varchar(500) NOT NULL,
  `CONTENT` longtext NOT NULL,
  `HIT_CNT` bigint(20) NOT NULL,
  `NOTICE_FLAG` char(1) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKqg1tqtible7kr9rhow7irpjub` (`BOARD_DEFAULT_MASTER_SEQ`),
  KEY `FKheda6jtecmjn32ljnevlb27qe` (`EDIT_USER_ID`),
  KEY `FK7m6frtcrh3c15wp4avacf721` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TECC_BOARD_DEFAULT_FILE` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `FILE_PATH` varchar(500) NOT NULL,
  `FILE_NAME` varchar(200) NOT NULL,
  `FILE_SIZE` bigint(20) NOT NULL,
  `THUM_FLAG` char(1) NOT NULL,
  `DOWN_CNT` int(11) NOT NULL,
  `BOARD_DEFAULT_SLAVE_SEQ` int(11) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKegv4l6q0aas4q1gi0elt02ed3` (`BOARD_DEFAULT_SLAVE_SEQ`),
  KEY `FKgewur2mu90ptm1vj7bp4sop1v` (`EDIT_USER_ID`),
  KEY `FKo4l7b2ggr84trqvcoobktsq75` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TEDA_BOARD_FAQ_MASTER` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `MASTER_NAME` varchar(20) NOT NULL,
  `MASTER_DESC` varchar(500) DEFAULT NULL,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKr0japjxcf8k3puvr7xtyxpkxf` (`EDIT_USER_ID`),
  KEY `FKvpkmksehc2s3ieodd6b1w1o2` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TEDB_BOARD_FAQ_SLAVE` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_CATEGORY_TYPE` varchar(10) NOT NULL,
  `BOARD_FAQ_MASTER_SEQ` int(11) DEFAULT NULL,
  `QUESTION` longtext NOT NULL,
  `ANSWER` longtext NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKcid498v5yumee1264s6aliyyo` (`BOARD_FAQ_MASTER_SEQ`),
  KEY `FKnn48cyulkh0fbv3x92dbofgyb` (`EDIT_USER_ID`),
  KEY `FKcqf6exr3tv0fsmkqtnmllp8cx` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TEEA_BOARD_DB2_MAPPING` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `BOARD_SEQ` int(11) NOT NULL,
  `BOARD_TYPE` varchar(10) NOT NULL,
  `S014SEQ` bigint(20) NOT NULL,
  PRIMARY KEY (`SEQ`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TEZA_BOARD_INSPECTION` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(500) DEFAULT NULL,
  `CONTENT` longtext,
  `HIT_CNT` bigint(20) DEFAULT NULL,
  `USER_ID` varchar(30) DEFAULT NULL,
  `USER_NAME` varchar(30) DEFAULT NULL,
  `USER_EMAIL` varchar(100) DEFAULT NULL,
  `USER_IP` varchar(20) DEFAULT NULL,
  `CATEGORY` varchar(100) DEFAULT NULL,
  `REF` int(11) DEFAULT NULL,
  `STATUS` varchar(1) DEFAULT NULL,
  `ANSWER` longtext,
  `ANSWER_USER_NAME` varchar(30) DEFAULT NULL,
  `ANSWER_DATE` datetime DEFAULT NULL,
  `REG_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`SEQ`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TFAA_INSPECTION_REQUEST` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `TITLE` varchar(100) NOT NULL,
  `PRINT_ORDER` int(11) NOT NULL,
  `FILE_PATH` varchar(500) NOT NULL,
  `FILE_NAME` varchar(200) NOT NULL,
  `THUM_FLAG` char(1) NOT NULL,
  `THUM_FILE_PATH` varchar(500) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKi5bjm1g2trw9m8osfu7jewgur` (`EDIT_USER_ID`),
  KEY `FKkt6onb3ixwir2e43nre2a2629` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TFBA_INSP_TEST_EDIT` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `CODE_EDIT_ST_TYPE` varchar(10) NOT NULL,
  `F010GCD` varchar(5) NOT NULL,
  `TEST_NAME` varchar(100) NOT NULL,
  `T001SAV` varchar(20) NOT NULL,
  `T001CONT` longtext,
  `T001ETC` longtext,
  `T001REF` longtext,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKmltdnwc6ml40c3idpogk0so00` (`EDIT_USER_ID`),
  KEY `FK2y4m3y1ittoktt4w0dl46ombt` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TFCA_INSP_TEST_ENG` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `F010GCD` varchar(5) NOT NULL,
  `T001SAV` varchar(20) NOT NULL,
  `T001CONT` longtext,
  `T001ETC` longtext,
  `T001REF` longtext,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKqg2pv263jwco3ejb0qsmys8f9` (`EDIT_USER_ID`),
  KEY `FKbjb11bii382est6jau0p519t4` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8
;
CREATE TABLE `TFDA_INSP_VESSEL` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `TITLE` varchar(120) NOT NULL,
  `SUB_TITLE` varchar(120) DEFAULT NULL,
  `INSPECTION_NAME` varchar(200) NOT NULL,
  `CODE_VESSELSC_TYPE` varchar(10) NOT NULL,
  `COMMENT` varchar(500) NOT NULL,
  `FILE_PATH` varchar(500) NOT NULL,
  `PRINT_ORDER` int(11) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK322c1neiwi7ckllttne32di8v` (`EDIT_USER_ID`),
  KEY `FKnvaplqhpqgc1rihia6e8okqev` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TGAA_MAIN_ROLLING` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `CONTENT` varchar(500) NOT NULL,
  `URL` varchar(500) DEFAULT NULL,
  `PRINT_ORDER` int(11) NOT NULL,
  `PRINT_FLAG` char(1) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK2a023mnusang7na92inijh4c3` (`EDIT_USER_ID`),
  KEY `FKcth4gus9qnedft856rqhv67yd` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TGBA_MAIN_LOGO` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `CODE_LOGO_TYPE` varchar(10) NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `URL` varchar(500) DEFAULT NULL,
  `FILE_PATH` varchar(500) NOT NULL,
  `FILE_NAME` varchar(200) NOT NULL,
  `FILE_SIZE` bigint(20) NOT NULL,
  `START_DATE` datetime NOT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKlpwolvhppejmkg23fit4gft3q` (`EDIT_USER_ID`),
  KEY `FKdacydcb8s04op8q4lvphysk6a` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TGCA_MAIN_SUB_BANNER` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `CONTENT` varchar(500) NOT NULL,
  `URL` varchar(500) DEFAULT NULL,
  `FILE_PATH` varchar(500) NOT NULL,
  `PRINT_FLAG` char(1) NOT NULL,
  `PRINT_ORDER` int(11) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKk137x2vdkadpljvko81cntusn` (`EDIT_USER_ID`),
  KEY `FK9qqy2wqxoabgyvw85oj46wrcb` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TGDA_MAIN_BANNER` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `TITLE` varchar(100) NOT NULL,
  `CONTENT` varchar(500) NOT NULL,
  `URL` varchar(500) DEFAULT NULL,
  `FILE_PATH` varchar(500) NOT NULL,
  `PRINT_ORDER` int(11) NOT NULL,
  `PRINT_FLAG` char(1) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK5ahold5ff9tcvqjdx6firx4tf` (`EDIT_USER_ID`),
  KEY `FK9htc3pm8onr57gt679jjke9xa` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TGEA_MAIN_POPUP` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `CONTENT` longtext,
  `URL` varchar(500) DEFAULT NULL,
  `PRINT_FLAG` char(1) NOT NULL,
  `FILE_PATH` varchar(500) DEFAULT NULL,
  `START_DATE` datetime NOT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK2hqlyqfkqmvb03lh7wjdcbgyv` (`EDIT_USER_ID`),
  KEY `FK4jiog9ne887734nianqdlf45p` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `THAA_NETWORK_STAFFS` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(10) NOT NULL,
  `DIRECTOR_FLAG` char(1) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `IMAGE_PATH` varchar(500) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKc82aqm5e2o399bgrs1fs7gd3o` (`EDIT_USER_ID`),
  KEY `FKok7dcpvv557n4vc6w39ixsxf2` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `THAB_NETWORK_STAFFS_INFO` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `COMPANY` varchar(100) DEFAULT NULL,
  `DEPARTMENT` varchar(50) NOT NULL,
  `MOBILE_PHONE` varchar(15) NOT NULL,
  `FAX` varchar(15) DEFAULT NULL,
  `ADDRESS` varchar(100) DEFAULT NULL,
  `NETWORK_STAFFS_SEQ` int(11) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKaxnxtnsjf2wh39au8ogrlo4n9` (`EDIT_USER_ID`),
  KEY `FK2bcwtfh5350q592x8saryweo2` (`REG_USER_ID`),
  KEY `FKft74vk2ksqytd3c0jf8fqfrva` (`NETWORK_STAFFS_SEQ`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `THBA_MAPPING` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_NETWORK_TYPE` varchar(10) NOT NULL,
  `NETWORK_STAFFS_SEQ` int(11) DEFAULT NULL,
  `PRINT_ORDER` int(11) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK244yf7kq57ahlwwaxxux0wqff` (`EDIT_USER_ID`),
  KEY `FKbf22je49hd2mbqy7hsrksi1yr` (`REG_USER_ID`),
  KEY `FK3lj2hy5qty73vxm2ojimct1vl` (`NETWORK_STAFFS_SEQ`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TIAA_PROMOTION` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `CODE_PROMOTION_TYPE` varchar(10) NOT NULL,
  `TITLE` varchar(100) NOT NULL,
  `SUB_TITLE` varchar(50) DEFAULT NULL,
  `URL` varchar(500) DEFAULT NULL,
  `FILE_PATH` varchar(500) DEFAULT NULL,
  `FILE_NAME` varchar(200) DEFAULT NULL,
  `THUM_FILE_PATH` varchar(500) NOT NULL,
  `PRINT_FLAG` char(1) NOT NULL,
  `PRINT_ORDER` int(11) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK1xfq5ee7o7d76aabop697x3` (`EDIT_USER_ID`),
  KEY `FKmp917wbacepr341kcbegbkci1` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TIBA_EBOOK` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `CODE_CATEGORY_TYPE` varchar(10) NOT NULL,
  `TITLE` varchar(120) NOT NULL,
  `URL` varchar(500) NOT NULL,
  `THUM_FILE_PATH` varchar(500) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKbg51ngxayxwnb9o1bqagbe81t` (`EDIT_USER_ID`),
  KEY `FKajowiev1oadelthwhqir9fbsn` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TJAA_HEALTH_INFO` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `CODE_LANG_TYPE` varchar(10) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `SUB_TITLE` varchar(120) NOT NULL,
  `PRINT_FLAG` char(1) NOT NULL,
  `PRINT_ORDER` int(11) NOT NULL,
  `VIEW_COUNT` int(11) NOT NULL,
  `WRITER` varchar(20) NOT NULL,
  `INSPECTOR` varchar(50) NOT NULL,
  `INSPECTOR_CMT` varchar(50) NOT NULL,
  `IMG_TITLE_THUM_PATH` varchar(500) NOT NULL,
  `IMG_TITLE_THUM_NAME` varchar(100) NOT NULL,
  `IMG_CONTENT_PATH` varchar(500) NOT NULL,
  `IMG_CONTENT_NAME` varchar(500) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKht0wa9ig6ept7yppei9t4tbdh` (`EDIT_USER_ID`),
  KEY `FKessdmjscw7uiv8pq9pm8snt3b` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TJAB_HEALTH_INFO_SOURCE` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `SOURCE` varchar(100) NOT NULL,
  `URL` varchar(500) DEFAULT NULL,
  `COMMENT` varchar(100) DEFAULT NULL,
  `HEALTH_INFO_SEQ` int(11) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKb2tp4kfkj4wcfxqy3yel8k7se` (`EDIT_USER_ID`),
  KEY `FKgkfux5d0491yyjtrm4m029emk` (`HEALTH_INFO_SEQ`),
  KEY `FKacwn29hxy3f12aftdof6p0lh4` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TJBA_TEST_CODE` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `TEST_CODE` varchar(10) NOT NULL,
  `TEST_NAME` varchar(500) NOT NULL,
  `COMMENT` varchar(1000) NOT NULL,
  `HEALTH_INFO_SEQ` int(11) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKdn0ue1lavm1gvo0j1wl6iu3b0` (`EDIT_USER_ID`),
  KEY `FKc3fio0ai0h2v0cjwp6uhk5qv5` (`HEALTH_INFO_SEQ`),
  KEY `FKngwvvuywf26dl9obpynr6kl75` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TJBC_TEST_HARD_INFO` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `TEST_CODE` varchar(10) DEFAULT NULL,
  `COMMENT` varchar(1000) NOT NULL,
  `TEST_NAME` varchar(500) DEFAULT NULL,
  `SPECIMEN` varchar(50) DEFAULT NULL,
  `VOLUME` varchar(50) DEFAULT NULL,
  `TEST_METHOD` varchar(40) DEFAULT NULL,
  `TEST_DAY` varchar(50) DEFAULT NULL,
  `PROCESS_DAY` varchar(50) DEFAULT NULL,
  `HEALTH_INFO_SEQ` int(11) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `DELETE_FLAG` char(1) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKbd3w4pa4ju1lrsgoo1t9sk3cv` (`EDIT_USER_ID`),
  KEY `FKatn6cove8n0teyl18sddyxbny` (`HEALTH_INFO_SEQ`),
  KEY `FKphjkwfucgpb22b1lsdhmjatkr` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TZAA_LOG_ACCESS` (
  `SEQ` bigint(20) NOT NULL AUTO_INCREMENT,
  `MENU_SEQ` int(11) NOT NULL,
  `IP` varchar(20) NOT NULL,
  `USER_ID` varchar(20) DEFAULT NULL,
  `REG_DATE` datetime NOT NULL,
  PRIMARY KEY (`SEQ`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TZAB_LOG_ACCESS_TOTAL` (
  `SEQ` bigint(20) NOT NULL AUTO_INCREMENT,
  `LOG_YMD` varchar(8) NOT NULL,
  `USER_ID` varchar(20) DEFAULT NULL,
  `MENU_SEQ` int(11) NOT NULL,
  `ACCESS_COUNT` bigint(20) NOT NULL,
  PRIMARY KEY (`SEQ`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TZBA_LOG_EDIT` (
  `SEQ` bigint(20) NOT NULL AUTO_INCREMENT,
  `MENU_NAME` varchar(40) NOT NULL,
  `LOG_TYPE` varchar(5) NOT NULL,
  `CLASS_NAME` varchar(100) NOT NULL,
  `BEFORE_JSON` longtext,
  `AFTER_JSON` longtext NOT NULL,
  `EDIT_DATE` datetime NOT NULL,
  `EDIT_USER_ID` varchar(20) NOT NULL,
  `IP` varchar(20) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKyprcnbxajj88iylmbwhfwp54` (`EDIT_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `TZCA_LOG_ERROR` (
  `SEQ` bigint(20) NOT NULL AUTO_INCREMENT,
  `URL` varchar(100) NOT NULL,
  `MENU_NAME` varchar(50) DEFAULT NULL,
  `PARAM_JSON` longtext NOT NULL,
  `ERROR_MSG` longtext,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) DEFAULT NULL,
  `IP` varchar(20) NOT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FK547jeqame0y2ade4da4fhuykm` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE `TZDA_LOG_DEVICE_INFO` (
  `SEQ` bigint(20) NOT NULL AUTO_INCREMENT,
  `OS` varchar(20) NOT NULL,
  `BROWSER` varchar(20) NOT NULL,
  `IP` varchar(20) NOT NULL,
  `SCREEN_WIDTH` int(11) NOT NULL,
  `SCREEN_HEIGHT` int(11) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `REG_USER_ID` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `FKpjbcudqj28fj34t8bynui1qsw` (`REG_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE `TZDB_LOG_DEVICE_TOTAL` (
  `SEQ` bigint(20) NOT NULL AUTO_INCREMENT,
  `LOG_YMD` varchar(8) NOT NULL,
  `OS` varchar(20) NOT NULL,
  `BROWSER` varchar(20) NOT NULL,
  `SCREEN_WIDTH` int(11) NOT NULL,
  `SCREEN_HEIGHT` int(11) NOT NULL,
  `ACCESS_COUNT` bigint(20) NOT NULL,
  PRIMARY KEY (`SEQ`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;